import './globals.css';
import Header from './components/Header';
import { ThemeProvider } from 'next-themes';
import ThemeCom from './components/ThemeCom';
import { ClerkProvider } from '@clerk/nextjs';
import Footer from './components/Footer';
import { Roboto } from 'next/font/google';

// Configure the Roboto font
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});

// Metadata for the application
export const metadata = {
  title: 'Developers Blog',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <head>
          {/* Add meta tags, links, or scripts here if needed */}
          <meta charSet='UTF-8' />
          <meta name='viewport' content='width=device-width, initial-scale=1.0' />
          <link rel='icon' href='/favicon.ico' />
        </head>
        <body
          className={`${roboto.className} flex flex-1 flex-col min-h-screen overflow-x-hidden`}
        >
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            <ThemeCom>
              <main className='flex flex-1 flex-col min-h-screen max-w-[1536px] mx-auto'>
                <Header />
                {children}
                <Footer />
              </main>
            </ThemeCom>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}